export const filterData=[
{name:"Vegetable", image:require("../assets/vegetable.png"),id:"0"},
{name:"Fruits", image:require("../assets/fruits.png"),id:"1"},
{name:"Vegetable Plants", image:require("../assets/vegplants.png"),id:"2"},
{name:"Fruits plants", image:require("../assets/fruitplant.png"),id:"3"},
{name:"Cooking Things", image:require("../assets/rice.png"),id:"4"},
{name:"Cleaning Things", image:require("../assets/washing.png"),id:"5"},
{name:"Education Things", image:require("../assets/book.png"),id:"6"}

];


export const restaurantsData = [
    {restaurantName:"Vegetables", farAway:"21.2",
    businessAddress:"22 Bessie street, Cape Town",images:'https://learnenglishfunway.com/wp-content/uploads/2020/12/Vegetables.jpg',
    averageReview:4.9,numberOfReview:272,coordinates : {lat: -26.1888612, lng: 28.246325} ,discount:10,deliveryTime:15,
    collectTime:5, foodType:"Burgers, Wraps,Milkshakes..." ,
    productData:[{name:"Hand cut chips", price:29.30,image:"https://bukasapics.s3.us-east-2.amazonaws.com/plate5.png"},
    {name:"Big Mac", price:50.80,image:"https://bukasapics.s3.us-east-2.amazonaws.com/plate4.png"},{name:"Chicken Burger",
     price:70,image:"https://bukasapics.s3.us-east-2.amazonaws.com/plate3.png"},
      ],
    id:0},
    
    {restaurantName:"Fruits", farAway:"12.7",businessAddress:"22 Bessie street, Cape Town",
    images:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2LyZeqfc6mzllmp2vqwt-ef5bplo2AQ33HQ&usqp=CAU',
    averageReview:4.3, numberOfReview:306, coordinates : {lat: -26.1891648, lng: 28.2441808},
    discount:20,deliveryTime:30,collectTime:10, foodType:"Chicken,Chicken wings... ",
    productData:[{name:"Hand cut chips", price:29.30,image:"https://bukasapics.s3.us-east-2.amazonaws.com/plate5.png"},
    {name:"Big Mac", price:50.80,image:"https://bukasapics.s3.us-east-2.amazonaws.com/plate4.png"},
    {name:"Chicken Burger", price:70,image:"https://bukasapics.s3.us-east-2.amazonaws.com/plate3.png"},
        ],
    id:1},
    
    {restaurantName:"Rice", farAway:"5",businessAddress:" 17 Olivia Rd, Johannesburg",
    images:'https://previews.123rf.com/images/navintar/navintar1610/navintar161000040/66833426-%E3%83%9C%E3%82%A6%E3%83%AB%E3%81%A8%E3%83%90%E3%83%83%E3%82%B0%E3%81%A8%E7%99%BD%E3%81%84%E8%83%8C%E6%99%AF%E3%81%A7%E6%9C%A8%E3%81%AE%E3%82%B9%E3%83%97%E3%83%BC%E3%83%B3%E3%81%A7%E7%99%BD%E7%B1%B3%E3%80%81%E3%82%B3%E3%83%94%E3%83%BC-%E3%82%B9%E3%83%9A%E3%83%BC%E3%82%B9%E5%B9%B3%E9%9D%A2%E5%9B%B3.jpg',
     coordinates :{ lat: -26.1886781, lng: 28.244879}, averageReview: 4.9,numberOfReview: 1272,
      discount:12, deliveryTime:25,collectTime:15,foodType:"Flame grilled beef Burgers",
     productData:[{name:"Hand cut chips", price:29.30,image:"https://bukasapics.s3.us-east-2.amazonaws.com/plate5.png"},
      {name:"Big Mac", price:50.80,image:"https://bukasapics.s3.us-east-2.amazonaws.com/plate4.png"},{name:"Chicken Burger",
       price:70,image:"https://bukasapics.s3.us-east-2.amazonaws.com/plate3.png"},
        ],
     id:2},
    
    {restaurantName:"Vegetable Plants", farAway:"7",businessAddress:" 15 Atlas Rd, Kempton Park",
    images:'https://d2xsikgwxkxyoe.cloudfront.net/media/55532/indoor-vegetable-garden-1543597148.jpg',
    averageReview:4.3, numberOfReview:700, coordinates: {lat: -26.1845336, lng: 28.2481691},
    discount:null,deliveryTime:20,collectTime:10,foodType:"Chicken pizza, Vegetarian pizza...",
    productData:[{name:"Hand cut chips", price:29.30,image:"https://bukasapics.s3.us-east-2.amazonaws.com/plate5.png"},
      {name:"Big Mac", price:50.80,image:"https://bukasapics.s3.us-east-2.amazonaws.com/plate4.png"},{name:"Chicken Burger",
       price:70,image:"https://bukasapics.s3.us-east-2.amazonaws.com/plate3.png"},
        ],
    id:3},
    ]


    export const recyclableProducts = [
      {restaurantName:"Books", farAway:"21.2",
      businessAddress:"22 Bessie street, Cape Town",images:'https://shop.alston.lk/wp-content/uploads/2020/06/3J0A2567.jpg',
      averageReview:4.9,numberOfReview:272,coordinates : {lat: -26.1888612, lng: 28.246325} ,discount:10,deliveryTime:15,
      collectTime:5, foodType:"Burgers, Wraps,Milkshakes..." ,
      productData:[{name:"Hand cut chips", price:29.30,image:"https://bukasapics.s3.us-east-2.amazonaws.com/plate5.png"},
      {name:"Big Mac", price:50.80,image:"https://bukasapics.s3.us-east-2.amazonaws.com/plate4.png"},{name:"Chicken Burger",
       price:70,image:"https://bukasapics.s3.us-east-2.amazonaws.com/plate3.png"},
        ],
      id:0},
      
      {restaurantName:"Washing Powder", farAway:"12.7",businessAddress:"22 Bessie street, Cape Town",
      images:'https://objectstorage.ap-mumbai-1.oraclecloud.com/n/softlogicbicloud/b/cdn/o/products/600-600/112900--01--1605146582.jpeg',
      averageReview:4.3, numberOfReview:306, coordinates : {lat: -26.1891648, lng: 28.2441808},
      discount:20,deliveryTime:30,collectTime:10, foodType:"Chicken,Chicken wings... ",
      productData:[{name:"Hand cut chips", price:29.30,image:"https://bukasapics.s3.us-east-2.amazonaws.com/plate5.png"},
      {name:"Big Mac", price:50.80,image:"https://bukasapics.s3.us-east-2.amazonaws.com/plate4.png"},
      {name:"Chicken Burger", price:70,image:"https://bukasapics.s3.us-east-2.amazonaws.com/plate3.png"},
          ],
      id:1},
      
      {restaurantName:"Water Bottel", farAway:"5",businessAddress:" 17 Olivia Rd, Johannesburg",
      images:'https://www.lalanka.com/images/3000/2308/bottled-drinking-waters?h=57df590b',
       coordinates :{ lat: -26.1886781, lng: 28.244879}, averageReview: 4.9,numberOfReview: 1272,
        discount:12, deliveryTime:25,collectTime:15,foodType:"Flame grilled beef Burgers",
       productData:[{name:"Hand cut chips", price:29.30,image:"https://bukasapics.s3.us-east-2.amazonaws.com/plate5.png"},
        {name:"Big Mac", price:50.80,image:"https://bukasapics.s3.us-east-2.amazonaws.com/plate4.png"},{name:"Chicken Burger",
         price:70,image:"https://bukasapics.s3.us-east-2.amazonaws.com/plate3.png"},
          ],
       id:2},
      
      {restaurantName:"Soaps", farAway:"7",businessAddress:" 15 Atlas Rd, Kempton Park",
      images:'https://doinikmudibazar.com/wp-content/uploads/2020/09/lux-bathing-soap.jpg',
      averageReview:4.3, numberOfReview:700, coordinates: {lat: -26.1845336, lng: 28.2481691},
      discount:null,deliveryTime:20,collectTime:10,foodType:"Chicken pizza, Vegetarian pizza...",
      productData:[{name:"Hand cut chips", price:29.30,image:"https://bukasapics.s3.us-east-2.amazonaws.com/plate5.png"},
        {name:"Big Mac", price:50.80,image:"https://bukasapics.s3.us-east-2.amazonaws.com/plate4.png"},{name:"Chicken Burger",
         price:70,image:"https://bukasapics.s3.us-east-2.amazonaws.com/plate3.png"},
          ],
      id:3},
      ]